version: '3'

services:
    testrun:
        build: .
        command: go run handler.go kademliaID.go lookup.go main.go network.go
        volumes:
            - ./src/main:/go/src/app
        working_dir: /go/src/app
        environment: 
            PORT: 3000